### ISSUE TITLE
[User feedback] Clarify how to configure ICSF for Zowe

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1073]
## Is your request for enhancement related to a problem? Please describe.

Feedback: Regarding Zowe installation guide, ICSF related section is too simple and too general, not so helpful for end user to install Zowe. 
 
## Describe the solution you'd like

Could you please add more detailed steps and description on how to configure that for Zowe installation to make it more user-friendly?

## Related doc pages

https://docs.zowe.org/stable/user-guide/install-nodejs-zos.html#hardware-and-software-requirements

## Additional context

ICSF is a prereq for Node.

**Comment by nannanli** [comment]
One option is to add links to the relevant ICSF books.

**Comment by NayerNajafi** [comment]
Hi @nannanli 
Here is the basic information about ICSF and why it should be available for Zowe in Z/OS:

* ICSF is a base element of z/OS and is included in z/OS package. It is not a Priced Feature. Each release of z/OS includes a particular ICSF FMID level as part of its base. For example, ICSF with FMID HCR77C0 is the base element of z/OS V2R3. 

* By default its SMP/E installed data sets has HLQ: CSF

* ICSF is not a prerequisite for Zowe, It is a prerequisite for IBM SDK for Node.js - z/OS. Since Zowe Application Framework (Zowe Desktop) requires Node.js, ICSF is a must.

* ICSF for Node.js requires neither Cryptographic Hardware nor Crypto cards.

**Comment by NayerNajafi** [comment]
@nannanli 
Here is some sort of minimal configuration to set up ICSF:

1- Add CSF.SCSFMOD0 to the LNKLST concatenation.

2- APF Authorize CSF.SCSFMOD0. 

3- Modify IKJTSOxx to add CSFDAUTH and CSFDPKDS in the AUTHPGM parameter list and in the AUTHTSF parameter list.

4- Create the following ICSF Key Data Sets:
- Cryptographic Key Data Set (CKDS) (Sample JCL: SYS1.SAMPLIB(CSFCKDS))
- Public Key Data Set (PKDS) (Sample JCL: SYS1.SAMPLIB(CSFPKDS))
- (Optional) If you desire to have PKCS#11 support through ICSF, you should create Token Key Data Set (TKDS) (Sample JCL: SYS1.SAMPLIB(CSFTKDS))

5- Copy ICSF Installation Options sample (SYS1.SAMPLIB(CSFPRM00)) to the system PARMLIB data set, and change the name of the data set on the CKDSN and PKDSN statements to the name of data sets you created previously.

6- Create ICSF startup procedure. Copy SYS1.SAMPLIB(CSF) to the system PROCLIB and change the data set name in the CSFPARM DD statement to the name of the installation options data set you provided previously.

7- (Optional) Define a RACF Started Procedure profile for CSF procedure in CLASS(STARTED).

8- Start ICSF (S CSF)

**Note:** You may need IPL before starting ICSF.
**Reference:** https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.csfb200/iandi.htm
