### ISSUE TITLE
Improve install documentation for the Upgrade scenario

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1263]
## Is your request for enhancement related to a problem? Please describe.
The install doc covers the initial install of a z/OS convenience build, SMP/E and z/OSMF workflow.
Customers who are doing upgrades of Zowe have told  me that the doc doesn't cover that scenario clearly enough,.

## Describe the solution you'd like
A documentation path that describes how to "upgrade" a Zowe instance

**Comment by John-A-Davies** [comment]
Here is an item of Text to be included in this section:

Introduction

There's a security change we need to make in the next release that depends upon configuring zowe to know the external host name(s) as opposed to any other name the system is known by, in the case that there's proxying/virtualization going on. If there is, it's possible that pre-existing configuration will not work, and action is needed to update the config. 

Action you should take

If you are upgrading to zowe xxx from a previous release, and the value of ZOWE_EXPLORER_HOST does not match the host and domain that you put into your browser to access Zowe, then you must update your configuration due to updated referrer-based security. You can either:
Define ZWE_EXTERNAL_HOSTS equal to a comma-separated list of hosts you would access Zowe from your browser
Or define ZWE_REFERRER_HOSTS the same way, for the value to be applied specifically for referrer purposes

**Comment by nannanli** [comment]
From @1000TurquoisePogs in issue #1441 . Moving the content here so we can work in a single issue. 

Many have figured out that you can upgrade zowe on z/os by just installing it again. However, it's not that simple and there are install steps that are not necessary to do again, as well as lack of knowledge on whether servers must be restarted during the upgrade process, and what happens to plugins.

This slack thread covers what we know at the moment and may be a good starting point
https://openmainframeproject.slack.com/archives/CC961JYMQ/p1601671582006700

In case that gets lost, here are some highlights
Upgrade steps to skip or focus on:
You DONT need to redo many of the ESM permissions
You DO need to rerun the create instance script, but on the existing instance
You MAY want to rerun the create keystore script, but only if there's some new feature around keystores that was added in the release. That sort of thing should be called out in the release notes

Service Disruption during Upgrades:
Upgrades to Zowe or plugins of Zowe can have varying degrees of service disruption due to the need to stop and restart STCs and processes.The impact depends upon whether Zowe itself is upgraded, or if it is a plugin.Zowe Server Upgrades:When Zowe is upgraded, STCs and processes are restarted. This will cause active operations to fail but idle or passive operations such as an open webpage may continue to work without disruption under the following circumstances:    SSO is being used
    SSO is not being used, but a new page in the browser is opened to re-login to ZoweIn both cases, the original webpages will have access to currently valid credentials, allowing the web page to issue new operations without needing a page reload.However, in-progress operations that failed during the upgrade, unless retried manually or automatically, may necessitate a page reload regardless. This may be the case for plugins and therefore must be understood on a case-by-case basis.Zowe Plugin Upgrades:Zowe plugins can depend in servers, databases, and other software that is outside the scope of Zowe. Therefore, you must refer to each plugin's documentation to understand what to expect when an upgrade occurs. However, here are some possible scenarios:    If the plugin uses the App Server to provide a REST api, disruption will occur if the app server must be restarted (causing the same behavior as a Zowe server upgrade), but admins can invoke the RBAC-controlled App Server endpoint "/server/reload" to reload the server without need for webpage reload. This endpoint and more are swagger documented here https://github.com/zowe/zlux-app-server/blob/staging/doc/swagger/server-plugins-api.yaml
    If the plugin uses the ZSS server to provide a REST api, ZSS must be restarted, causing the same disruption behavior as a Zowe server upgrade.
    If the plugin has web content that shows in the Desktop via iframe, you can open a new instance of the app in the existing Desktop to see that new content.
    If the plugin has web content that shows in the Desktop without an iframe, you must reload the Desktop to see that next content.
    If the plugin depends upon a database or server external to Zowe, you must consult the plugin's documentation on what to expect.

![image](https://user-images.githubusercontent.com/30730276/95231142-c6830780-07d0-11eb-968f-5b9a7b15d030.png)

restarts:
zowe doesnt manage the shutdown/startup during the install process, but the user must do that.

**Comment by Joe-Winchester** [comment]
@nannanli - I think we can close this issue off as 1.17 includes an integration chapter now.  Do you think there needs to be any changes to the diagram for the install flow to cover upgrade, or we should close this issue as-is ?

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, I was thinking of creating an upgrade checklist or path based on existing content to help users but that can be a different issue. For the upgrade itself, we can close this issue now.
