### ISSUE TITLE
Copy Zowe install cmd from section 7.2.1 of the COBOL-Programming-Course fails to run in command line

### ISSUE THREAD

**Issue by banjaxxer** [zowe/docs-site#1285]
## Description

**Given** you are using the **COBOL-Programming-Course-1-Getting-Started.pdf guide** on page **44** to install Zowe CLI
**When** you copy the command in _section 7.2.1_ to run
 _npm install -g @zowe/cli@zowe -v1-lts_ and paste it into the command line and press enter
**Then** You see the following results.

```
npm install -g @zowe/cli@zowe -v1-lts
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @zowe/cli@zowe.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevepbolton/.npm/_logs/2020-06-24T11_26_23_531Z-debug.log
```

Note that the command _npm install -g @zowe/cli@zowe-v1-lts_ from https://docs.zowe.org/stable/user-guide/cli-installcli.html#installing-zowe-cli-from-an-online-registry does work.

## Expected behavior

Zowe should install.

## Additional context

Looking at it again I can see there is a space between **zowe** and **-v1** causing the problem.

**Comment by nannanli** [comment]
Thank you for raising this doc defect! This issue belongs to the https://github.com/openmainframeproject/cobol-programming-course repo. Just checked that this issue has been fixed in the documentation so I'll close this issue. See the updated topic [here](https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20Course%20%231%20-%20Getting%20Started/COBOL%20Programming%20Course%20%231%20-%20Getting%20Started.md#install-from-public-npm-registry).
