### ISSUE TITLE
How will we handle z/OS 2.2 Support ending September

### ISSUE THREAD

**Issue by nkocsis** [zowe/docs-site#1389]
Please update the documentation to reflect changes.

https://github.com/zowe/zowe-install-packaging/issues/1630

**Comment by Joe-Winchester** [comment]
The doc chapter 
https://docs.zowe.org/stable/user-guide/systemrequirements.html#z-os-system-requirements-host
will need updating as it currently says 

![image](https://user-images.githubusercontent.com/28100302/92912781-0cdb8580-f422-11ea-870b-45052c63b547.png)

We should do this for the 1.16 release and merge early into master.

**Comment by nannanli** [comment]
@Joe-Winchester @1000TurquoisePogs  The end of support date is approaching. I'm wondering if we should update the online doc now to say something like the following one: 

## z/OS system requirements (host) 
- z/OS Version 2.2 or later. 
  **Note:** z/OS V2.2 reaches end of support on September 30th, 2020. For more information, see the [z/OS v2.2 lifecycle details]( https://www.ibm.com/support/lifecycle/details?q45=Z497063S01245B61) in the IBM Support website. You are advised to upgrade your z/OS to more recent versions.

**Comment by Joe-Winchester** [comment]
@nannanli - yes that's a great idea.  I know @nkocsis and Bruce Armstrong have been thinking about this also and it'd be great to get it into 1.16 release,  maybe even merge it live into master before then if possible.

**Comment by nkocsis** [comment]
I seem to remember from our discussion (Architecture Call) that we were going to tell people that the support for this has expired but to also point them to these details here ->: https://www.ibm.com/support/lifecycle/details?q45=Z497063S01245B61

There might be some customers that would pay for continued support so we don't want to tell them that they are not support ... It should be left for them to decide but I remember Sean mentioning that the server will get some message in the logs on startup that their OS has reached end of support (EOS)

**Comment by jordanCain** [comment]
@nannanli After further discussion with Joe and Bruce I think we want to be more assertive in this case as Zowe moves forwards it requires features delivered in PTFs that are only available in z/OS 2.3 and 2.4.  

So instead of having "z/OS Version 2.2 or later." we should move to something along the lines of "z/OS Version current in active support such as z/OS 2.3 and z/OS 2.4" We could chose to leave in the note referencing end of support for 2.2 and calling out that previous versions of Zowe were happy with 2.2 but going forward that is no longer the case
