### ISSUE TITLE
Broken link in https://docs.zowe.org/v1.28.x/extend/extend-desktop/mvd-uribroker/

### ISSUE THREAD

**Issue by skurnevich** [zowe/docs-site#2249]
From page: 
https://docs.zowe.org/v1.28.x/extend/extend-desktop/mvd-uribroker/

Link:
[Application plug-in filesystem structure](https://docs.zowe.org/v1.28.x/extend/extend-desktop/mvd-uribroker/mvd-plugindefandstruct#application-plug-in-filesystem-structure)

Same behaviour for [stable](https://docs.zowe.org/stable/extend/extend-desktop/mvd-uribroker/) version

**Comment by JamesBauman** [comment]
Note to file - the link is defective in the subsequent releases:  2.0 and 2.1.

**Comment by nannanli** [comment]
Currently, the link is using`[Application plug-in filesystem structure](mvd-plugindefandstruct#application-plug-in-filesystem-structure)` . However, note that the dash `-` between `plug` and `in` has been removed based on the target section so it should be `[Application plug-in filesystem structure](mvd-plugindefandstruct#application-plugin-filesystem-structure)` now. This should be fixed in all online Zowe doc versions. Perhaps do a quick search and replace.

**Comment by lparadkar-rocket** [comment]
I replaced it in 12 instances. Will push the changes now.

**Comment by anaxceron** [comment]
Closing b/c this issue has been resolved on the live site. (If anyone tests this in the future, do not use the "From page" link provided above. Use [this link](https://docs.zowe.org/v1.28.x/extend/extend-desktop/mvd-uribroker) instead.)
