### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/advanced-apiml-configuration/

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3730]
## Description

[Customizing management of API ML load limits](https://docs.zowe.org/stable/user-guide/advanced-apiml-configuration/api-mediation/configuration-customizing-management-of-apiml-load-limits) leads to a 404

**Comment by balhar-jakub** [comment]
The correct link is: https://docs.zowe.org/stable/user-guide/api-mediation/configuration-customizing-management-of-apiml-load-limits 

@janan07 This seems like some kind of general problem. If you go to the advanced configuration via https://docs.zowe.org/stable/user-guide/advanced-apiml-configuration/ instead of https://docs.zowe.org/stable/user-guide/advanced-apiml-configuration the links break down.

**Comment by janan07** [comment]
Please see https://github.com/zowe/docs-site/pull/3734 to address this issue and update the content of this article.
