### ISSUE TITLE
Rename MVD and zLUX

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#59]
There is discussion to rename these two terms. Created this issue to track the doc impact.

**Comment by 1000TurquoisePogs** [comment]
zLUX is still zLUX from a codebase and technical troubleshooting point of view, but in terms of end user terminology, zLUX is the Zowe App Framework which enables Zowe Apps, and MVD is the Zowe Desktop.

**Comment by jhenryRocket** [comment]
Renamed " zLUX Application Server" to "Zowe Application Server" (otherwise it would be the Zowe Application Framework Application Server, which is long and somewhat redundant)

Renamed "zLUX Proxy Server" to "Zowe Proxy Server" (I didn't see any other proxy servers)

**Comment by 1000TurquoisePogs** [comment]
I think those two things are identical: zlux has one server, in code it is the zlux-proxy-server but to users it's the Zowe App Server.

**Comment by jhenryRocket** [comment]
OK - thanks!

**Comment by jhenryRocket** [comment]
Hi @nannanli, there will be significant impact to the documentation because there are markdown file names such as usingzlux.md that will need to be renamed to usingzoweappframework.md so they display in the URL appropriately. In the markdown files, there are also links to some headings that will need to be updated. 

MVD  --> Zowe Desktop
zLUX  --> Zowe Application Framework
(zLUX Application Server/zLUX Proxy Server ) ---> Zowe Application Server

**Comment by nannanli** [comment]
Hi Julie, thanks for the update! This sounds a complex work. Besides the renaming of zLUX/MVD in User Guide, zLUX/MVD in tutorials and samples should also be renamed. Perhaps a quick find and replace using Notepad is a good way. 
For the broken links that will be brought by this change, we can run broken link checker to check and correct if any. Cathy recommended a tool http://wummel.github.io/linkchecker/ which we can run locally to check.

**Comment by jhenryRocket** [comment]
So, zlux references will remain in the developer documentation because...
zlux is a codebase name so technical documentation on it doesn't need to change. just less technical documentation that considers it to be the zowe ui

Regarding servers, I encountered a reference to a "zLUX window manager server" in the "Installing the Zowe runtime on z/OS" section of the user guide.  (The context is: "zLUX-server has three ports - the HTTP and HTTPS ports that are used by the zLUX window manager server, and the port that is used by the ZSS server.") -- I think this is supposed to be "Zowe Application Server"

I found the following references to RocketMVD (in the developer doc) - I didn't find any references to RocketMVD in the user topics.

window.parent.RocketMVD.
RocketMVD.PluginManager
parent.RocketMVD
window.RocketMVD.uriBroker
window.parent.RocketMVD.uriBroker
