### ISSUE TITLE
Document how to extend the Zowe Desktop after zLUX componentization

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#849]
When https://github.com/zowe/zowe-install-packaging/issues/627 and https://github.com/zowe/zowe-install-packaging/issues/741 are complete in v1.8, the way that users extend Zowe Desktop is going to change. Need to document the new procedure. 

### Related page
https://docs.zowe.org/stable/extend/extend-desktop/mvd-extendingzlux.html

This page is an overview of how to extend Zowe Desktop and it has two tutorials.

**Comment by NakulManchanda** [comment]
@1000TurquoisePogs  updated readme of  `zowe/zlux-app-server` repo as part of  https://github.com/zowe/zowe-install-packaging/issues/627
Same PR done for componentisation also has documentation on how to setup development environment and new folder structure and new helper script which help to register plugins to zlux
https://github.com/zowe/zlux-app-server/pull/87

@nannanli @jasonenglish2039 FYI

**Comment by NakulManchanda** [comment]
[Tutorial 1](https://docs.zowe.org/stable/extend/extend-desktop/zlux-app-server.html#server-layout) should be updated based on 
[zlux-app-server staging readme](https://github.com/zowe/zlux-app-server/tree/staging) if not already. Its a direct copy of that i believe.

[Tutorial 2 ](https://docs.zowe.org/stable/extend/extend-desktop/zlux-workshop-user-browser.html#adding-your-app-to-the-desktop)  section Adding Your App to the Desktop needs updating as well if not already.

**Comment by nannanli** [comment]
Thanks @NakulManchanda ! I think Jason has completed most of the changes for this issue on the `docs-staging` branch via PR https://github.com/zowe/docs-site/pull/882. @jasonenglish2039 Could you check Nakul's comments and confirm? Thanks!

**Comment by jasonenglish2039** [comment]
@1000TurquoisePogs told me about this a few weeks ago and I made a lot of updates to the "Developing for Application Framework" section in #882 based on Sean's updates to the [wiki](https://github.com/1000TurquoisePogs/zlux/wiki). But I did NOT update the tutorials.

I have a suggestion: instead of me basically copying and pasting the tutorials from README docs into the documentation, why don't I remove them and just link to the source? It just seems redundant to keep the same information in two places. The first tutorial is easy, I can just link [here](https://github.com/zowe/zlux-app-server/tree/staging), where Sean updated it. 

The [second tutorial](https://github.com/zowe/workshop-user-browser-app) is a bit puzzling, because Sean hasn't edited it since May last year. Are we sure it should be updated?

**Comment by nannanli** [comment]
@jasonenglish2039 Agree, we should keep the tutorial content in one location. 1) Either remove the content from doc site and link to the GitHub repo, or 2) keep it on the doc site (using the doc site Markdown file as the single location), remove the content in the GitHub repo and update the readme to link to the doc site.

**Comment by jasonenglish2039** [comment]
@nannanli I will remove the content from the doc site and replace it with links to the tutorials. I know we're publishing early this week so I'll do that now.

**Comment by jasonenglish2039** [comment]
These changes are in PR #931.

**Comment by NakulManchanda** [comment]
There is new EXTERNAL_COMPONENTS use to extend API ML and Zowe Desktop
https://github.com/zowe/sample-node-api
https://github.com/zowe/sample-trial-app
